In [12]:
import pandas as pd
import numpy as np

# Data Warehouses Datasets

On this notebook all used datasets are read and a initial data cleaning and data preparation is applied. The following summary provides the info that is kept from each read file.


#### Datasets Info Summary:

- *df_pop*:
    - time dimension: 2021-2024 (yearly)
    - space dimension: Porto metropolitan area

- *df_substations*: 
    - time: last updated in 6 March 2026

- *df_station_sp* and *df_station_pr*:
    - time dimension: 01/01/2022 - 28/02/2026 (daily)

- *df_consumption_pt1* and *df_consumption_pt2*:
    - time dimension: 01/02/2025 - 31/01/2026 (hourly)

- *df_charging*:
    - time dimension: January 2021 - December 2024 (monthly)
    - space dimension: Porto metropolitan area

# Population Dataset

Source: Instituto Nacional de Estatística (INE)

https://censos.ine.pt/xportal/xmain?xpid=INE&xpgid=ine_indicadores&userLoadSave=Load&userTableOrder=13050&tipoSeleccao=1&contexto=pq&selTab=tab1&submitLoad=true&xlang=pt

In [13]:
df_pop = pd.read_csv(
    "ine_population_data.csv",
    encoding="latin1",
    sep=";",
    skiprows=3
)

df_pop

,Período de referência dos dados (1),"NUTS 2024 (hierarquia cumulativa - PT, NUTS I, II, III, CC, FR) - variante 1 (2)",Taxa de crescimento efetivo (%) por Local de residência (NUTS - 2024) - Anual,Densidade populacional (N.º/ km²) por Local de residência (NUTS - 2024) - Anual,Cidades (N.º) por Localização geográfica (NUTS - 2024) - Anual,Freguesias (N.º) por Localização geográfica (NUTS - 2024) - Anual,Vilas (N.º) por Localização geográfica (NUTS - 2024) - Anual,Unnamed: 7
0,NaN,NaN,%,N.º/ km²,N.º,N.º,N.º,NaN
1,2024,11A: Área Metropolitana do Porto,"0,86","890,7",x,173,x,NaN
2,NaN,11A0104: Arouca,"-0,43","63,3",x,16,x,NaN
3,NaN,11A0107: Espinho,"1,05","1554,4",x,4,x,NaN
4,NaN,11A1304: Gondomar,"0,48",1284,x,7,x,NaN
...,...,...,...,...,...,...,...,...
175,Definição,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176,Fórmula,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177,Unidade de Medida (símbolo),Número (N.º),NaN,NaN,NaN,NaN,NaN,NaN
178,Potência de 10,0,NaN,NaN,NaN,NaN,NaN,NaN
179,Data da última atualização,27-Jun-2024,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df_pop.columns = [
    "year",
    "region",
    "growth_rate",
    "density",
    "cities",
    "freguesias",
    "vilas",
    "extra"  # last empty column
]

In [15]:
df_pop["year"] = df_pop["year"].ffill() #correct so all rows have an assigned year
df_pop

,year,region,growth_rate,density,cities,freguesias,vilas,extra
0,NaN,NaN,%,N.º/ km²,N.º,N.º,N.º,NaN
1,2024,11A: Área Metropolitana do Porto,"0,86","890,7",x,173,x,NaN
2,2024,11A0104: Arouca,"-0,43","63,3",x,16,x,NaN
3,2024,11A0107: Espinho,"1,05","1554,4",x,4,x,NaN
4,2024,11A1304: Gondomar,"0,48",1284,x,7,x,NaN
...,...,...,...,...,...,...,...,...
175,Definição,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176,Fórmula,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177,Unidade de Medida (símbolo),Número (N.º),NaN,NaN,NaN,NaN,NaN,NaN
178,Potência de 10,0,NaN,NaN,NaN,NaN,NaN,NaN
179,Data da última atualização,27-Jun-2024,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
# Temporarily show all rows
with pd.option_context('display.max_rows', None):
    display(df_pop)

,year,region,growth_rate,density,cities,freguesias,vilas,extra
0,NaN,NaN,%,N.º/ km²,N.º,N.º,N.º,NaN
1,2024,11A: Área Metropolitana do Porto,"0,86","890,7",x,173,x,NaN
2,2024,11A0104: Arouca,"-0,43","63,3",x,16,x,NaN
3,2024,11A0107: Espinho,"1,05","1554,4",x,4,x,NaN
4,2024,11A1304: Gondomar,"0,48",1284,x,7,x,NaN
5,2024,11A1306: Maia,"1,44",1744,x,10,x,NaN
6,2024,11A1308: Matosinhos,"0,83","2900,4",x,4,x,NaN
7,2024,11A0113: Oliveira de Azeméis,"0,29","418,8",x,12,x,NaN
8,2024,11A1310: Paredes,"0,63","552,2",x,18,x,NaN
9,2024,11A1312: Porto,"1,56","6100,6",x,7,x,NaN
10,2024,11A1313: Póvoa de Varzim,"1,37","832,7",x,7,x,NaN
11,2024,11A0109: Santa Maria da Feira,"0,52","651,1",x,21,x,NaN
12,2024,11A1314: Santo Tirso,"-0,17","495,8",x,14,x,NaN
13,2024,11A0116: São João da Madeira,"1,6","3053,8",x,1,x,NaN
14,2024,11A1318: Trofa,"0,74","559,6",x,5,x,NaN
15,2024,11A0119: Vale de Cambra,"-0,06","144,2",x,7,x,NaN
16,2024,11A1315: Valongo,"1,29","1350,7",x,4,x,NaN
17,2024,11A1316: Vila do Conde,"1,17","576,2",x,21,x,NaN
18,2024,11A1317: Vila Nova de Gaia,"0,56","1857,9",x,15,x,NaN
19,2023,11A: Área Metropolitana do Porto,"1,27","883,1",27,173,69,NaN
20,2023,11A0104: Arouca,"-0,12","63,6",0,16,1,NaN
21,2023,11A0107: Espinho,"1,58","1538,1",1,4,2,NaN
22,2023,11A1304: Gondomar,"0,79","1277,9",3,7,2,NaN
23,2023,11A1306: Maia,"1,6",1719,1,10,3,NaN
24,2023,11A1308: Matosinhos,"1,35","2876,6",3,4,5,NaN
25,2023,11A0113: Oliveira de Azeméis,"0,61","417,6",1,12,8,NaN
26,2023,11A1310: Paredes,"0,74","548,7",4,18,6,NaN
27,2023,11A1312: Porto,"2,34",6006,1,7,0,NaN
28,2023,11A1313: Póvoa de Varzim,"1,89","821,4",1,7,3,NaN
29,2023,11A0109: Santa Maria da Feira,"0,92","647,8",3,21,13,NaN
30,2023,11A1314: Santo Tirso,"0,18","496,7",1,14,6,NaN
31,2023,11A0116: São João da Madeira,"2,18","3005,4",1,1,0,NaN
32,2023,11A1318: Trofa,"1,05","555,5",1,5,1,NaN
33,2023,11A0119: Vale de Cambra,"0,03","144,2",1,7,2,NaN
34,2023,11A1315: Valongo,"1,77","1333,4",3,4,2,NaN
35,2023,11A1316: Vila do Conde,"1,59","569,5",1,21,0,NaN
36,2023,11A1317: Vila Nova de Gaia,"0,87","1847,5",1,15,15,NaN
37,2022,11A: Área Metropolitana do Porto,"1,37",872,x,x,x,NaN
38,2022,11A0104: Arouca,"-0,47","63,6",x,x,x,NaN
39,2022,11A0107: Espinho,"1,4",1514,x,x,x,NaN
40,2022,11A1304: Gondomar,"0,95","1267,8",x,x,x,NaN
41,2022,11A1306: Maia,"1,97","1691,8",x,x,x,NaN
42,2022,11A1308: Matosinhos,"1,42","2837,9",x,x,x,NaN
43,2022,11A0113: Oliveira de Azeméis,"0,38","415,1",x,x,x,NaN
44,2022,11A1310: Paredes,"0,48","544,7",x,x,x,NaN
45,2022,11A1312: Porto,"2,93","5867,1",x,x,x,NaN
46,2022,11A1313: Póvoa de Varzim,"1,75",806,x,x,x,NaN
47,2022,11A0109: Santa Maria da Feira,"0,86","641,8",x,x,x,NaN
48,2022,11A1314: Santo Tirso,"0,06","495,8",x,x,x,NaN
49,2022,11A0116: São João da Madeira,"2,42","2940,6",x,x,x,NaN
50,2022,11A1318: Trofa,"1,47","549,7",x,x,x,NaN
51,2022,11A0119: Vale de Cambra,"-0,21","144,2",x,x,x,NaN
52,2022,11A1315: Valongo,"1,81",1310,x,x,x,NaN
53,2022,11A1316: Vila do Conde,"1,75","560,5",x,x,x,NaN
54,2022,11A1317: Vila Nova de Gaia,"0,86","1831,5",x,x,x,NaN
55,2021,11A: Área Metropolitana do Porto,"0,72","860,2",x,x,x,NaN
56,2021,11A0104: Arouca,"-0,95","63,9",x,x,x,NaN
57,2021,11A0107: Espinho,"0,85","1492,9",x,x,x,NaN
58,2021,11A1304: Gondomar,"0,45","1255,9",x,x,x,NaN
59,2021,11A1306: Maia,"1,58","1658,8",x,x,x,NaN
60,2021,11A1308: Matosinhos,"0,81","2797,9",x,x,x,NaN
61,2021,11A0113: Oliveira de Azeméis,"0,24","413,5",x,x,x,NaN
62,2021,11A1310: Paredes,"0,31","542,1",x,x,x,NaN
63,2021,11A1312: Porto,"1,34","5697,8",x,x,x,NaN
64,2021,11A1313: Póvoa de Varzim,"0,91",792,x,x,x,NaN
65,2021,11A0109: Santa Maria da Feira,"0,1","636,3",x,x,x,NaN
66,2021,11A1314: Santo Tirso,"-0,48","495,5",x,x,x,NaN
67,2021,11A0116: São João da Madeira,"2,39","2870,2",x,x,x,NaN
68,2021,11A1318: Trofa,"0,88","541,7",x,x,x,NaN
69,2021,11A0119: Vale de Cambra,"-0,26","144,5",x,x,x,NaN
70,2021,11A1315: Valongo,"1,7","1286,6",x,x,x,NaN
71,2021,11A1316: Vila do Conde,"1,03","550,8",x,x,x,NaN
72,2021,11A1317: Vila Nova de Gaia,"0,31","1815,9",x,x,x,NaN
73,Taxa de crescimento efetivo (%) por Local de r...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,Densidade populacional (N.º/ km²) por Local de...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,Cidades (N.º) por Localização geográfica (NUTS...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,Freguesias (N.º) por Localização geográfica (N...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,Vilas (N.º) por Localização geográfica (NUTS -...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,Nota(s):,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,(1) Estimativas Provisórias de População Resid...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,"<BR>2022, Estimativas Provisórias de População...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,(2) Estimativas de População Residente segundo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,Última atualização destes dados: 14 de agosto ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,Metainformação associada ao quadro,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,Taxa de crescimento efetivo (%),NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,Designação,Taxa de crescimento efetivo (%) por Local de r...,NaN,NaN,NaN,NaN,NaN,NaN
86,Periodicidade,Anual,NaN,NaN,NaN,NaN,NaN,NaN
87,Fonte,"INE, Indicadores demográficos",NaN,NaN,NaN,NaN,NaN,NaN
88,Primeiro período disponível,2021,NaN,NaN,NaN,NaN,NaN,NaN
89,Último período disponível,2024,NaN,NaN,NaN,NaN,NaN,NaN
90,Dimensões,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,Dimensão 1,Período de referência dos dados,NaN,NaN,NaN,NaN,NaN,NaN
92,Dimensão 2,Local de residência (NUTS - 2024),NaN,NaN,NaN,NaN,NaN,NaN
93,Conceitos,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,POPULAÇÃO MÉDIA,População calculada pela média aritmética dos ...,NaN,NaN,NaN,NaN,NaN,NaN
95,PERÍODO DE REFERÊNCIA,Período a que a informação se refere e que pod...,NaN,NaN,NaN,NaN,NaN,NaN
96,TAXA DE CRESCIMENTO EFETIVO,Variação populacional observada durante um det...,NaN,NaN,NaN,NaN,NaN,NaN
97,Definição,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,Fórmula,&lt - p&gt - TCE=[[P(t)-P(t-1)]/[P(t)+P(t-1)]/...,NaN,NaN,NaN,NaN,NaN,NaN
99,Unidade de Medida (símbolo),Percentagem (%),NaN,NaN,NaN,NaN,NaN,NaN
100,Potência de 10,0,NaN,NaN,NaN,NaN,NaN,NaN
101,Data da última atualização,18-Jun-2025,NaN,NaN,NaN,NaN,NaN,NaN
102,Densidade populacional (N.º/ km²),NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,Designação,Densidade populacional (N.º/ km²) por Local de...,NaN,NaN,NaN,NaN,NaN,NaN
104,Periodicidade,Anual,NaN,NaN,NaN,NaN,NaN,NaN
105,Fonte,"INE, Estimativas anuais da população residente",NaN,NaN,NaN,NaN,NaN,NaN
106,Primeiro período disponível,2021,NaN,NaN,NaN,NaN,NaN,NaN
107,Último período disponível,2024,NaN,NaN,NaN,NaN,NaN,NaN
108,Dimensões,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,Dimensão 1,Período de referência dos dados,NaN,NaN,NaN,NaN,NaN,NaN
110,Dimensão 2,Local de residência (NUTS - 2024),NaN,NaN,NaN,NaN,NaN,NaN
111,Conceitos,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,PERÍODO DE REFERÊNCIA,Período a que a informação se refere e que pod...,NaN,NaN,NaN,NaN,NaN,NaN
113,POPULAÇÃO RESIDENTE,"Conjunto de pessoas que, independentemente de ...",NaN,NaN,NaN,NaN,NaN,NaN
114,DENSIDADE POPULACIONAL,Intensidade do povoamento expressa pela relaçã...,NaN,NaN,NaN,NaN,NaN,NaN
115,Definição,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,Fórmula,Total de indivíduos/ Área (quilómetro quadrado),NaN,NaN,NaN,NaN,NaN,NaN
117,Unidade de Medida (símbolo),Número/ Quilómetro quadrado (N.º/ km²),NaN,NaN,NaN,NaN,NaN,NaN
118,Potência de 10,0,NaN,NaN,NaN,NaN,NaN,NaN
119,Data da última atualização,05-Aug-2025,NaN,NaN,NaN,NaN,NaN,NaN
120,Cidades (N.º),NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,Designação,Cidades (N.º) por Localização geográfica (NUTS...,NaN,NaN,NaN,NaN,NaN,NaN
122,Periodicidade,Anual,NaN,NaN,NaN,NaN,NaN,NaN
123,Fonte,"INE, Sistema integrado de nomenclaturas estatí...",NaN,NaN,NaN,NaN,NaN,NaN
124,Primeiro período disponível,2023,NaN,NaN,NaN,NaN,NaN,NaN
125,Último período disponível,2023,NaN,NaN,NaN,NaN,NaN,NaN
126,Dimensões,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,Dimensão 1,Período de referência dos dados,NaN,NaN,NaN,NaN,NaN,NaN
128,Dimensão 2,Localização geográfica (NUTS - 2024),NaN,NaN,NaN,NaN,NaN,NaN
129,Conceitos,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,PERÍODO DE REFERÊNCIA,Período a que a informação se refere e que pod...,NaN,NaN,NaN,NaN,NaN,NaN
131,CIDADE,"Aglomerado populacional contínuo, com um númer...",farmácias,corporação de bombeiros,casa de espetáculos e centro cultural,NaN,NaN,NaN
132,museu e biblioteca,instalações de hotelaria,estabelecimentos de ensino preparatório e sec...,estabelecimentos de ensino pré-primário e inf...,"transportes públicos, urbanos e suburbanos",parques ou jardins públicos.,NaN,NaN
133,Definição,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,Fórmula,NaN,NaN,NaN,NaN,NaN,NaN,NaN
135,Unidade de Medida (símbolo),Número (N.º),NaN,NaN,NaN,NaN,NaN,NaN
136,Potência de 10,0,NaN,NaN,NaN,NaN,NaN,NaN
137,Data da última atualização,27-Jun-2024,NaN,NaN,NaN,NaN,NaN,NaN
138,Freguesias (N.º),NaN,NaN,NaN,NaN,NaN,NaN,NaN
139,Designação,Freguesias (N.º) por Localização geográfica (N...,NaN,NaN,NaN,NaN,NaN,NaN
140,Periodicidade,Anual,NaN,NaN,NaN,NaN,NaN,NaN
141,Fonte,"INE, Sistema integrado de nomenclaturas estatí...",NaN,NaN,NaN,NaN,NaN,NaN
142,Primeiro período disponível,2023,NaN,NaN,NaN,NaN,NaN,NaN
143,Último período disponível,2024,NaN,NaN,NaN,NaN,NaN,NaN
144,Dimensões,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145,Dimensão 1,Período de referência dos dados,NaN,NaN,NaN,NaN,NaN,NaN
146,Dimensão 2,Localização geográfica (NUTS - 2024),NaN,NaN,NaN,NaN,NaN,NaN
147,Conceitos,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148,FREGUESIA,Circunscrição administrativa em que se subdivi...,NaN,NaN,NaN,NaN,NaN,NaN
149,PERÍODO DE REFERÊNCIA,Período a que a informação se refere e que pod...,NaN,NaN,NaN,NaN,NaN,NaN
150,Definição,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151,Fórmula,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152,Unidade de Medida (símbolo),Número (N.º),NaN,NaN,NaN,NaN,NaN,NaN
153,Potência de 10,0,NaN,NaN,NaN,NaN,NaN,NaN
154,Data da última atualização,14-Aug-2025,NaN,NaN,NaN,NaN,NaN,NaN
155,Vilas (N.º),NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,Designação,Vilas (N.º) por Localização geográfica (NUTS -...,NaN,NaN,NaN,NaN,NaN,NaN
157,Periodicidade,Anual,NaN,NaN,NaN,NaN,NaN,NaN
158,Fonte,"INE, Sistema integrado de nomenclaturas estatí...",NaN,NaN,NaN,NaN,NaN,NaN
159,Primeiro período disponível,2023,NaN,NaN,NaN,NaN,NaN,NaN
160,Último período disponível,2023,NaN,NaN,NaN,NaN,NaN,NaN
161,Dimensões,NaN,NaN,NaN,NaN,NaN,NaN,NaN
162,Dimensão 1,Período de referência dos dados,NaN,NaN,NaN,NaN,NaN,NaN
163,Dimensão 2,Localização geográfica (NUTS - 2024),NaN,NaN,NaN,NaN,NaN,NaN
164,Conceitos,NaN,NaN,NaN,NaN,NaN,NaN,NaN
165,VILA,"Aglomerado populacional contínuo, com um númer...",NaN,NaN,NaN,NaN,NaN,NaN
166,a) Posto de assistência médica,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167,b) Farmácia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168,"c) Casa do Povo, dos Pescadores, de espetáculo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,d) Transportes públicos coletivos,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,e) Estação dos CTT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
171,f) Estabelecimentos comerciais e de hotelaria,NaN,NaN,NaN,NaN,NaN,NaN,NaN
172,g) Estabelecimento que ministre escolaridade o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
173,h) Agência bancária,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174,PERÍODO DE REFERÊNCIA,Período a que a informação se refere e que pod...,NaN,NaN,NaN,NaN,NaN,NaN
175,Definição,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176,Fórmula,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177,Unidade de Medida (símbolo),Número (N.º),NaN,NaN,NaN,NaN,NaN,NaN
178,Potência de 10,0,NaN,NaN,NaN,NaN,NaN,NaN
179,Data da última atualização,27-Jun-2024,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df_pop = df_pop.iloc[0:73] #select the data of interest
df_pop

,year,region,growth_rate,density,cities,freguesias,vilas,extra
0,NaN,NaN,%,N.º/ km²,N.º,N.º,N.º,NaN
1,2024,11A: Área Metropolitana do Porto,"0,86","890,7",x,173,x,NaN
2,2024,11A0104: Arouca,"-0,43","63,3",x,16,x,NaN
3,2024,11A0107: Espinho,"1,05","1554,4",x,4,x,NaN
4,2024,11A1304: Gondomar,"0,48",1284,x,7,x,NaN
...,...,...,...,...,...,...,...,...
68,2021,11A1318: Trofa,"0,88","541,7",x,x,x,NaN
69,2021,11A0119: Vale de Cambra,"-0,26","144,5",x,x,x,NaN
70,2021,11A1315: Valongo,"1,7","1286,6",x,x,x,NaN
71,2021,11A1316: Vila do Conde,"1,03","550,8",x,x,x,NaN
72,2021,11A1317: Vila Nova de Gaia,"0,31","1815,9",x,x,x,NaN

In [18]:
#Instead of having region with the code and name, transform it into 2 columns
df_pop[["region_code", "region_name"]] = df_pop["region"].str.split(":", n=1, expand=True)
df_pop = df_pop.drop('region', axis=1) #delete region column
df_pop

C:\Users\InesNeves\AppData\Local\Temp\ipykernel_34992\2040895892.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pop[["region_code", "region_name"]] = df_pop["region"].str.split(":", n=1, expand=True)
C:\Users\InesNeves\AppData\Local\Temp\ipykernel_34992\2040895892.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pop[["region_code", "region_name"]] = df_pop["region"].str.split(":", n=1, expand=True)

,year,growth_rate,density,cities,freguesias,vilas,extra,region_code,region_name
0,NaN,%,N.º/ km²,N.º,N.º,N.º,NaN,NaN,NaN
1,2024,"0,86","890,7",x,173,x,NaN,11A,Área Metropolitana do Porto
2,2024,"-0,43","63,3",x,16,x,NaN,11A0104,Arouca
3,2024,"1,05","1554,4",x,4,x,NaN,11A0107,Espinho
4,2024,"0,48",1284,x,7,x,NaN,11A1304,Gondomar
...,...,...,...,...,...,...,...,...,...
68,2021,"0,88","541,7",x,x,x,NaN,11A1318,Trofa
69,2021,"-0,26","144,5",x,x,x,NaN,11A0119,Vale de Cambra
70,2021,"1,7","1286,6",x,x,x,NaN,11A1315,Valongo
71,2021,"1,03","550,8",x,x,x,NaN,11A1316,Vila do Conde
72,2021,"0,31","1815,9",x,x,x,NaN,11A1317,Vila Nova de Gaia

In [19]:
# checking null values
df_pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73 entries, 0 to 72
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   year         72 non-null     object
 1   growth_rate  73 non-null     object
 2   density      73 non-null     object
 3   cities       73 non-null     object
 4   freguesias   73 non-null     object
 5   vilas        73 non-null     object
 6   extra        0 non-null      float64
 7   region_code  72 non-null     object
 8   region_name  72 non-null     object
dtypes: float64(1), object(8)
memory usage: 5.3+ KB

In [20]:
#Since the column extra is all null values, we can delete it
df_pop = df_pop.drop('extra', axis=1)

In [21]:
df_pop

,year,growth_rate,density,cities,freguesias,vilas,region_code,region_name
0,NaN,%,N.º/ km²,N.º,N.º,N.º,NaN,NaN
1,2024,"0,86","890,7",x,173,x,11A,Área Metropolitana do Porto
2,2024,"-0,43","63,3",x,16,x,11A0104,Arouca
3,2024,"1,05","1554,4",x,4,x,11A0107,Espinho
4,2024,"0,48",1284,x,7,x,11A1304,Gondomar
...,...,...,...,...,...,...,...,...
68,2021,"0,88","541,7",x,x,x,11A1318,Trofa
69,2021,"-0,26","144,5",x,x,x,11A0119,Vale de Cambra
70,2021,"1,7","1286,6",x,x,x,11A1315,Valongo
71,2021,"1,03","550,8",x,x,x,11A1316,Vila do Conde
72,2021,"0,31","1815,9",x,x,x,11A1317,Vila Nova de Gaia

In [22]:
# Get all names of Area Metropolitan of Porto, municipalities
df_pop["region_name"] = df_pop["region_name"].str.strip() # Remove spaces in the begining and the end of the region names
unique_regions = df_pop["region_name"].dropna().unique().tolist()
display(unique_regions)

['Área Metropolitana do Porto',
 'Arouca',
 'Espinho',
 'Gondomar',
 'Maia',
 'Matosinhos',
 'Oliveira de Azeméis',
 'Paredes',
 'Porto',
 'Póvoa de Varzim',
 'Santa Maria da Feira',
 'Santo Tirso',
 'São João da Madeira',
 'Trofa',
 'Vale de Cambra',
 'Valongo',
 'Vila do Conde',
 'Vila Nova de Gaia']

In [13]:
df_pop.to_csv('cleaned_ine_population_data.csv')

# Secondary Substations (PTD) Dataset

Geographic locations of the substations in the distribution network, including information on installed capacity and utilization rates.

Source: https://e-redes.opendatasoft.com/explore/dataset/postos-transformacao-distribuicao/information/?flg=en-en

In [22]:
df_substations = pd.read_csv("postos-transformacao-distribuicao.csv", sep=";")
df_substations

,Installation Code,District,Municipality,Geographic Coordinates,Installed Power [kVA],Usage Level [%],Construction Type,Contracted Power [kVA],Number of Clients,Power Generation [kW],Number of Client Producers,Usage Histogram,DistrictCode,DistrictMunicipalityCode
0,1106D1546700,Lisboa,Lisboa,"38.736184093666424, -9.162444301064484",320,20%-39%,Cabine baixa em edifício próprio,N/D,<20,N/D,<20,(0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;1329....,11,1106
1,1106D1167200,Lisboa,Lisboa,"38.75699559503596, -9.154127348388766",630,0%-19%,Cabine baixa integrada em edifício,N/D,<20,N/D,<20,(0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;8325....,11,1106
2,1106D1952700,Lisboa,Lisboa,"38.74225077052723, -9.20200726059019",630,20%-39%,Cabine baixa em edifício próprio,1280.53,144,N/D,<20,(0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;95.25...,11,1106
3,1106D1596700,Lisboa,Lisboa,"38.757479098038985, -9.18842584108611",630,20%-39%,Cabine subterrânea,1701.70,241,N/D,<20,(0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;2611....,11,1106
4,1106D1085400,Lisboa,Lisboa,"38.72255878357668, -9.132513037586431",1130,40%-59%,Cabine baixa integrada em edifício,4003.24,633,N/D,<20,(0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.5;4...,11,1106
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72344,1607D2031200,Viana do Castelo,Ponte de Lima,"41.670156085443764, -8.548560973026538",160,20%-39%,Aéreo - AI,216.20,25,N/D,<20,(0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;1.75;592....,16,1607
72345,0809D2005100,Faro,Monchique,"37.24463416494255, -8.501421593206965",50,20%-39%,Aéreo - AS,N/D,<20,N/D,<20,(0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;6821....,8,809
72346,0908D2001400,Guarda,Manteigas,"40.40600005966807, -7.565260352658387",100,40%-59%,Cabine baixa em edifício próprio,310.09,32,N/D,<20,(0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;1.0;1...,9,908
72347,0103D2021900,Aveiro,Anadia,"40.46129511002289, -8.439256620149731",630,0%-19%,Cabine pré-fabricada,N/D,<20,N/D,<20,(0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;8567....,1,103
72348,1709D3004900,Vila Real,Ribeira de Pena,"41.5419644964358, -7.807125970728252",100,20%-39%,Aéreo - AS,457.89,102,N/D,<20,(0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;183.5...,17,1709

In [23]:
# Choose the substations that are within the Porto Metropolitan Area
df_substations = df_substations[df_substations["Municipality"].isin(unique_regions)]
df_substations

,Installation Code,District,Municipality,Geographic Coordinates,Installed Power [kVA],Usage Level [%],Construction Type,Contracted Power [kVA],Number of Clients,Power Generation [kW],Number of Client Producers,Usage Histogram,DistrictCode,DistrictMunicipalityCode
28,1312D2103700,Porto,Porto,"41.183677856847204, -8.608945507725844",630,0%-19%,Cabine metálica (monobloco),1317.35,201,N/D,<20,(0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;5359....,13,1312
35,1316D2004400,Porto,Vila do Conde,"41.336527228320506, -8.645671024999814",400,20%-39%,Cabine alta,1610.01,216,N/D,<20,(0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;3.25;...,13,1316
36,1316D2016800,Porto,Vila do Conde,"41.27164654205575, -8.724611320666718",630,20%-39%,Cabine baixa em edifício próprio,2047.95,336,N/D,<20,(0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;7.75;...,13,1316
37,1316D2057000,Porto,Vila do Conde,"41.279717670991126, -8.679046573660683",400,0%-19%,Cabine pré-fabricada,N/D,<20,N/D,<20,(0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;1.5;8290....,13,1316
39,1317D2070300,Porto,Vila Nova de Gaia,"41.04344892828184, -8.542996018121055",250,20%-39%,Cabine baixa em edifício próprio,640.00,71,N/D,<20,(0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;575.5...,13,1317
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72317,0113D2008400,Aveiro,Oliveira de Azeméis,"40.78512433492829, -8.467140436977383",400,20%-39%,Cabine pré-fabricada,1089.14,153,N/D,<20,(0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;910.5...,1,113
72318,0113D2007900,Aveiro,Oliveira de Azeméis,"40.890482619464066, -8.513090092169527",400,20%-39%,Cabine baixa em edifício próprio,1382.89,188,N/D,<20,(0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;4119....,1,113
72319,0113D2025000,Aveiro,Oliveira de Azeméis,"40.78321708858559, -8.482865377918259",250,20%-39%,Cabine baixa em edifício próprio,513.32,50,N/D,<20,(0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;1802....,1,113
72320,0113D2010000,Aveiro,Oliveira de Azeméis,"40.84480155852852, -8.460583166128844",400,0%-19%,Cabine alta,N/D,<20,N/D,<20,(0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;8741....,1,113
72321,1315D2029800,Porto,Valongo,"41.18428330069614, -8.480504222883171",630,0%-19%,Cabine pré-fabricada,N/D,<20,N/D,<20,(0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;8315....,13,1315

In [24]:
df_substations.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8412 entries, 28 to 72321
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Installation Code           8412 non-null   object
 1   District                    8412 non-null   object
 2   Municipality                8412 non-null   object
 3   Geographic Coordinates      8412 non-null   object
 4   Installed Power [kVA]       8412 non-null   int64
 5   Usage Level [%]             8412 non-null   object
 6   Construction Type           8412 non-null   object
 7   Contracted Power [kVA]      8412 non-null   object
 8   Number of Clients           8412 non-null   object
 9   Power Generation [kW]       8412 non-null   object
 10  Number of Client Producers  8412 non-null   object
 11  Usage Histogram             8068 non-null   object
 12  DistrictCode                8412 non-null   int64
 13  DistrictMunicipalityCode    8412 non-null   int64
dtypes: int64(3), object(11)
memory usage: 985.8+ KB

In [26]:
df_substations.to_csv('cleaned_postos-transformacao-distribuicao.csv')

# Weather Stations Dataset

This site has two weather stations in Porto, one in Serra do Pilar (Vila Nova de Gaia, Porto) and another one in Pedras Rubras (Maia, Porto).

Source: 
- Serra do Pilar: https://meteostat.net/pt/place/pt/porto?s=08546&t=2022-01-01/2026-02-28
- Pedras Rubras: https://meteostat.net/pt/place/pt/porto?s=08545&t=2022-01-01/2026-02-28#google_vignette

In [2]:
df_station_sp = pd.read_csv("porto_serra_do_pilar_weather.csv")
df_station_pr= pd.read_csv("porto_pedras_rubras_weather.csv")

In [3]:
print("Serra do Pilar")
display(df_station_sp)

print("Pedras Rubras")
display(df_station_pr)

Serra do Pilar

,date,tavg,tmin,tmax,prcp,snow,wdir,wspd,wpgt,pres,tsun
0,2022-01-01 00:00:00,16.4,11.6,23.7,0.0,NaN,NaN,14.9,29.6,1025.3,NaN
1,2022-01-02 00:00:00,13.8,10.9,23.7,4.3,NaN,NaN,7.4,24.1,1029.7,NaN
2,2022-01-03 00:00:00,11.9,8.8,17.2,0.3,NaN,NaN,13.4,33.3,1025.5,NaN
3,2022-01-04 00:00:00,12.1,8.5,15.3,9.7,NaN,NaN,14.7,44.5,1018.4,NaN
4,2022-01-05 00:00:00,9.7,7.1,13.3,10.4,NaN,NaN,8.9,31.5,1022.3,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1515,2026-02-24 00:00:00,13.0,10.3,17.4,0.0,NaN,NaN,13.1,31.5,1017.1,NaN
1516,2026-02-25 00:00:00,12.6,10.4,14.3,4.6,NaN,NaN,9.7,27.8,1017.1,NaN
1517,2026-02-26 00:00:00,11.6,9.1,16.4,0.0,NaN,NaN,7.1,25.9,1024.5,NaN
1518,2026-02-27 00:00:00,9.9,7.5,12.5,3.3,NaN,NaN,10.3,25.9,1025.4,NaN
1519,2026-02-28 00:00:00,9.0,6.1,13.5,0.0,NaN,NaN,12.4,33.3,1026.5,NaN

Pedras Rubras

,date,tavg,tmin,tmax,prcp,snow,wdir,wspd,wpgt,pres,tsun
0,2022-01-01 00:00:00,18.0,14.3,22.5,NaN,NaN,NaN,18.9,33.3,1023.8,NaN
1,2022-01-02 00:00:00,13.9,10.6,16.6,NaN,NaN,NaN,9.5,27.8,1028.8,NaN
2,2022-01-03 00:00:00,12.0,9.3,13.9,NaN,NaN,NaN,15.3,40.8,1024.3,NaN
3,2022-01-04 00:00:00,11.9,9.7,15.0,NaN,NaN,NaN,22.0,46.3,1017.1,NaN
4,2022-01-05 00:00:00,9.8,7.3,13.4,NaN,NaN,NaN,11.8,33.3,1021.1,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1515,2026-02-24 00:00:00,13.4,11.1,15.0,0.0,NaN,NaN,10.3,35.2,1016.6,NaN
1516,2026-02-25 00:00:00,13.4,11.0,16.0,3.6,NaN,NaN,7.0,33.3,1017.1,NaN
1517,2026-02-26 00:00:00,11.2,8.0,16.0,0.0,NaN,NaN,3.9,27.8,1024.2,NaN
1518,2026-02-27 00:00:00,11.4,8.0,14.0,3.1,NaN,NaN,8.5,29.6,1024.9,NaN
1519,2026-02-28 00:00:00,9.4,5.0,15.0,0.0,NaN,NaN,7.5,37.0,1026.3,NaN

In [4]:
# Extracting year, month, day and time

df_station_sp["date"] = pd.to_datetime(df_station_sp["date"])
df_station_sp["year"] = df_station_sp["date"].dt.year
df_station_sp["month"] = df_station_sp["date"].dt.month
df_station_sp["day"] = df_station_sp["date"].dt.day
df_station_sp["time"] = df_station_sp["date"].dt.time


df_station_pr["date"] = pd.to_datetime(df_station_pr["date"])
df_station_pr["year"] = df_station_pr["date"].dt.year
df_station_pr["month"] = df_station_pr["date"].dt.month
df_station_pr["day"] = df_station_pr["date"].dt.day
df_station_pr["time"] = df_station_pr["date"].dt.time

display(df_station_sp)
display(df_station_pr)

,date,tavg,tmin,tmax,prcp,snow,wdir,wspd,wpgt,pres,tsun,year,month,day,time
0,2022-01-01,16.4,11.6,23.7,0.0,NaN,NaN,14.9,29.6,1025.3,NaN,2022,1,1,00:00:00
1,2022-01-02,13.8,10.9,23.7,4.3,NaN,NaN,7.4,24.1,1029.7,NaN,2022,1,2,00:00:00
2,2022-01-03,11.9,8.8,17.2,0.3,NaN,NaN,13.4,33.3,1025.5,NaN,2022,1,3,00:00:00
3,2022-01-04,12.1,8.5,15.3,9.7,NaN,NaN,14.7,44.5,1018.4,NaN,2022,1,4,00:00:00
4,2022-01-05,9.7,7.1,13.3,10.4,NaN,NaN,8.9,31.5,1022.3,NaN,2022,1,5,00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1515,2026-02-24,13.0,10.3,17.4,0.0,NaN,NaN,13.1,31.5,1017.1,NaN,2026,2,24,00:00:00
1516,2026-02-25,12.6,10.4,14.3,4.6,NaN,NaN,9.7,27.8,1017.1,NaN,2026,2,25,00:00:00
1517,2026-02-26,11.6,9.1,16.4,0.0,NaN,NaN,7.1,25.9,1024.5,NaN,2026,2,26,00:00:00
1518,2026-02-27,9.9,7.5,12.5,3.3,NaN,NaN,10.3,25.9,1025.4,NaN,2026,2,27,00:00:00
1519,2026-02-28,9.0,6.1,13.5,0.0,NaN,NaN,12.4,33.3,1026.5,NaN,2026,2,28,00:00:00

,date,tavg,tmin,tmax,prcp,snow,wdir,wspd,wpgt,pres,tsun,year,month,day,time
0,2022-01-01,18.0,14.3,22.5,NaN,NaN,NaN,18.9,33.3,1023.8,NaN,2022,1,1,00:00:00
1,2022-01-02,13.9,10.6,16.6,NaN,NaN,NaN,9.5,27.8,1028.8,NaN,2022,1,2,00:00:00
2,2022-01-03,12.0,9.3,13.9,NaN,NaN,NaN,15.3,40.8,1024.3,NaN,2022,1,3,00:00:00
3,2022-01-04,11.9,9.7,15.0,NaN,NaN,NaN,22.0,46.3,1017.1,NaN,2022,1,4,00:00:00
4,2022-01-05,9.8,7.3,13.4,NaN,NaN,NaN,11.8,33.3,1021.1,NaN,2022,1,5,00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1515,2026-02-24,13.4,11.1,15.0,0.0,NaN,NaN,10.3,35.2,1016.6,NaN,2026,2,24,00:00:00
1516,2026-02-25,13.4,11.0,16.0,3.6,NaN,NaN,7.0,33.3,1017.1,NaN,2026,2,25,00:00:00
1517,2026-02-26,11.2,8.0,16.0,0.0,NaN,NaN,3.9,27.8,1024.2,NaN,2026,2,26,00:00:00
1518,2026-02-27,11.4,8.0,14.0,3.1,NaN,NaN,8.5,29.6,1024.9,NaN,2026,2,27,00:00:00
1519,2026-02-28,9.4,5.0,15.0,0.0,NaN,NaN,7.5,37.0,1026.3,NaN,2026,2,28,00:00:00

In [6]:
print("Serra do Pilar")
display(df_station_sp.info())

print("Pedras Rubras")
display(df_station_pr.info())

Serra do Pilar
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1520 entries, 0 to 1519
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1520 non-null   datetime64[ns]
 1   tavg    1520 non-null   float64
 2   tmin    1520 non-null   float64
 3   tmax    1520 non-null   float64
 4   prcp    1407 non-null   float64
 5   snow    0 non-null      float64
 6   wdir    0 non-null      float64
 7   wspd    1520 non-null   float64
 8   wpgt    1508 non-null   float64
 9   pres    1520 non-null   float64
 10  tsun    0 non-null      float64
 11  year    1520 non-null   int32
 12  month   1520 non-null   int32
 13  day     1520 non-null   int32
 14  time    1520 non-null   object
dtypes: datetime64[ns](1), float64(10), int32(3), object(1)
memory usage: 160.4+ KB

None

Pedras Rubras
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1520 entries, 0 to 1519
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1520 non-null   datetime64[ns]
 1   tavg    1520 non-null   float64
 2   tmin    1520 non-null   float64
 3   tmax    1520 non-null   float64
 4   prcp    1349 non-null   float64
 5   snow    0 non-null      float64
 6   wdir    0 non-null      float64
 7   wspd    1520 non-null   float64
 8   wpgt    1508 non-null   float64
 9   pres    1520 non-null   float64
 10  tsun    0 non-null      float64
 11  year    1520 non-null   int32
 12  month   1520 non-null   int32
 13  day     1520 non-null   int32
 14  time    1520 non-null   object
dtypes: datetime64[ns](1), float64(10), int32(3), object(1)
memory usage: 160.4+ KB

None

In [7]:
# We can delete the columns "snow", "wdir" and "tsun" because they have all values as null
df_station_sp = df_station_sp.drop(columns=["snow", "wdir", "tsun"])
df_station_pr = df_station_pr.drop(columns=["snow", "wdir", "tsun"])

print("Serra do Pilar")
display(df_station_sp)
print("Pedras Rubras")
display(df_station_pr)

Serra do Pilar

,date,tavg,tmin,tmax,prcp,wspd,wpgt,pres,year,month,day,time
0,2022-01-01,16.4,11.6,23.7,0.0,14.9,29.6,1025.3,2022,1,1,00:00:00
1,2022-01-02,13.8,10.9,23.7,4.3,7.4,24.1,1029.7,2022,1,2,00:00:00
2,2022-01-03,11.9,8.8,17.2,0.3,13.4,33.3,1025.5,2022,1,3,00:00:00
3,2022-01-04,12.1,8.5,15.3,9.7,14.7,44.5,1018.4,2022,1,4,00:00:00
4,2022-01-05,9.7,7.1,13.3,10.4,8.9,31.5,1022.3,2022,1,5,00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
1515,2026-02-24,13.0,10.3,17.4,0.0,13.1,31.5,1017.1,2026,2,24,00:00:00
1516,2026-02-25,12.6,10.4,14.3,4.6,9.7,27.8,1017.1,2026,2,25,00:00:00
1517,2026-02-26,11.6,9.1,16.4,0.0,7.1,25.9,1024.5,2026,2,26,00:00:00
1518,2026-02-27,9.9,7.5,12.5,3.3,10.3,25.9,1025.4,2026,2,27,00:00:00
1519,2026-02-28,9.0,6.1,13.5,0.0,12.4,33.3,1026.5,2026,2,28,00:00:00

Pedras Rubras

,date,tavg,tmin,tmax,prcp,wspd,wpgt,pres,year,month,day,time
0,2022-01-01,18.0,14.3,22.5,NaN,18.9,33.3,1023.8,2022,1,1,00:00:00
1,2022-01-02,13.9,10.6,16.6,NaN,9.5,27.8,1028.8,2022,1,2,00:00:00
2,2022-01-03,12.0,9.3,13.9,NaN,15.3,40.8,1024.3,2022,1,3,00:00:00
3,2022-01-04,11.9,9.7,15.0,NaN,22.0,46.3,1017.1,2022,1,4,00:00:00
4,2022-01-05,9.8,7.3,13.4,NaN,11.8,33.3,1021.1,2022,1,5,00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
1515,2026-02-24,13.4,11.1,15.0,0.0,10.3,35.2,1016.6,2026,2,24,00:00:00
1516,2026-02-25,13.4,11.0,16.0,3.6,7.0,33.3,1017.1,2026,2,25,00:00:00
1517,2026-02-26,11.2,8.0,16.0,0.0,3.9,27.8,1024.2,2026,2,26,00:00:00
1518,2026-02-27,11.4,8.0,14.0,3.1,8.5,29.6,1024.9,2026,2,27,00:00:00
1519,2026-02-28,9.4,5.0,15.0,0.0,7.5,37.0,1026.3,2026,2,28,00:00:00

In [8]:
df_station_sp.to_csv('cleaned_porto_serra_do_pilar_weather.csv')
df_station_pr.to_csv('cleaned_porto_pedras_rubras_weather.csv')

# Hourly Consumption Electric Mobility Dataset

The E-Redes Database divides the complete dataset into two datasets. And both of them are needed because Porto Metropolitan Area has municipalities from both Porto's and Aveiro's Districts.

Source: https://e-redes.opendatasoft.com/explore/dataset/consumo_horario_mobilidade_eletrica/table/

In [9]:
df_consumption_pt1= pd.read_csv("consumo_horario_mobilidade_eletrica_01_a_10.csv", sep=";")
df_consumption_pt2= pd.read_csv("consumo_horario_mobilidade_eletrica_11_a_18.csv", sep=";")

In [10]:
display(df_consumption_pt1)
display(df_consumption_pt2)

,Date/Time,Date,Hour,District,Municipality,Parish,Energy Consumed,District Code,Municipality Code,Parish Code,group_name,Dia,Mês,Ano
0,2025-10-01T05:00:00+01:00,2025-10-01,04:00,Aveiro,Santa Maria da Feira,Milheirós de Poiares,0.00,1,109,010914,01_a_10,1,10,2025
1,2025-10-05T00:00:00+01:00,2025-10-04,23:00,Aveiro,Santa Maria da Feira,Milheirós de Poiares,0.00,1,109,010914,01_a_10,4,10,2025
2,2025-10-29T15:00:00+00:00,2025-10-29,15:00,Braga,Guimarães,Serzedelo,0.00,3,308,030866,01_a_10,29,10,2025
3,2025-10-24T11:00:00+01:00,2025-10-24,10:00,Braga,Guimarães,Serzedelo,0.00,3,308,030866,01_a_10,24,10,2025
4,2025-10-03T00:00:00+01:00,2025-10-02,23:00,Castelo Branco,Idanha-a-Nova,Medelim,0.00,5,505,050506,01_a_10,2,10,2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4948508,2025-09-17T17:00:00+01:00,2025-09-17,16:00,Faro,Albufeira,Guia,49.42,8,801,080102,01_a_10,17,9,2025
4948509,2025-09-21T14:00:00+01:00,2025-09-21,13:00,Braga,Barcelos,Rio Covo (Santa Eugénia),0.00,3,302,030265,01_a_10,21,9,2025
4948510,2025-09-22T03:00:00+01:00,2025-09-22,02:00,Braga,Barcelos,Rio Covo (Santa Eugénia),0.00,3,302,030265,01_a_10,22,9,2025
4948511,2025-09-21T14:00:00+01:00,2025-09-21,13:00,Aveiro,Oliveira de Azeméis,Nogueira do Cravo e Pindelo,0.00,1,113,011320,01_a_10,21,9,2025
4948512,2025-09-19T12:00:00+01:00,2025-09-19,11:00,Braga,Vila Nova de Famalicão,Brufe,0.00,3,312,031206,01_a_10,19,9,2025

,Date/Time,Date,Hour,District,Municipality,Parish,Energy Consumed,District Code,Municipality Code,Parish Code,group_name,Dia,Mês,Ano
0,2025-10-18T07:00:00+01:00,2025-10-18,06:00,Vila Real,Chaves,"Vidago, Arcossó, Selhariz, Vilarinho Paranheiras",0.00,17,1703,170361,11_a_18,18,10,2025
1,2025-10-14T21:00:00+01:00,2025-10-14,20:00,Vila Real,Chaves,"Vidago, Arcossó, Selhariz, Vilarinho Paranheiras",0.00,17,1703,170361,11_a_18,14,10,2025
2,2025-10-26T07:00:00+00:00,2025-10-26,07:00,Vila Real,Chaves,"Vidago, Arcossó, Selhariz, Vilarinho Paranheiras",0.00,17,1703,170361,11_a_18,26,10,2025
3,2025-10-08T22:00:00+01:00,2025-10-08,21:00,Lisboa,Alenquer,Carnota,0.00,11,1101,110106,11_a_18,8,10,2025
4,2025-10-09T15:00:00+01:00,2025-10-09,14:00,Vila Real,Chaves,"Vidago, Arcossó, Selhariz, Vilarinho Paranheiras",0.00,17,1703,170361,11_a_18,9,10,2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4366696,2026-01-23T09:00:00+00:00,2026-01-23,09:00,Vila Real,Chaves,"Vidago, Arcossó, Selhariz, Vilarinho Paranheiras",0.00,17,1703,170361,11_a_18,23,1,2026
4366697,2026-01-13T21:00:00+00:00,2026-01-13,21:00,Lisboa,Alenquer,Carnota,0.00,11,1101,110106,11_a_18,13,1,2026
4366698,2026-01-09T17:00:00+00:00,2026-01-09,17:00,Lisboa,Vila Franca de Xira,Castanheira do Ribatejo e Cachoeiras,17.03,11,1114,111414,11_a_18,9,1,2026
4366699,2026-01-05T22:00:00+00:00,2026-01-05,22:00,Lisboa,Vila Franca de Xira,Castanheira do Ribatejo e Cachoeiras,4.42,11,1114,111414,11_a_18,5,1,2026
4366700,2026-01-26T17:00:00+00:00,2026-01-26,17:00,Lisboa,Vila Franca de Xira,Castanheira do Ribatejo e Cachoeiras,51.69,11,1114,111414,11_a_18,26,1,2026

In [ ]:
# Select only the rows that belong to Area Metropolitan of Porto
df_consumption_pt1 = df_consumption_pt1[df_consumption_pt1["Municipality"].isin(unique_regions)]
df_consumption_pt2 = df_consumption_pt2[df_consumption_pt2["Municipality"].isin(unique_regions)]

In [24]:
display(df_consumption_pt1)
display(df_consumption_pt2)

,Date/Time,Date,Hour,District,Municipality,Parish,Energy Consumed,District Code,Municipality Code,Parish Code,group_name,Dia,Mês,Ano
0,2025-10-01T05:00:00+01:00,2025-10-01,04:00,Aveiro,Santa Maria da Feira,Milheirós de Poiares,0.00,1,109,010914,01_a_10,1,10,2025
1,2025-10-05T00:00:00+01:00,2025-10-04,23:00,Aveiro,Santa Maria da Feira,Milheirós de Poiares,0.00,1,109,010914,01_a_10,4,10,2025
29,2025-10-26T23:00:00+00:00,2025-10-26,23:00,Aveiro,Santa Maria da Feira,Milheirós de Poiares,0.00,1,109,010914,01_a_10,26,10,2025
50,2025-10-22T04:00:00+01:00,2025-10-22,03:00,Aveiro,Santa Maria da Feira,Milheirós de Poiares,0.00,1,109,010914,01_a_10,22,10,2025
51,2025-10-10T12:00:00+01:00,2025-10-10,11:00,Aveiro,Santa Maria da Feira,Milheirós de Poiares,0.00,1,109,010914,01_a_10,10,10,2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4948483,2025-09-02T12:00:00+01:00,2025-09-02,11:00,Aveiro,Santa Maria da Feira,"Lobão, Gião, Louredo e Guisande",0.00,1,109,010934,01_a_10,2,9,2025
4948484,2025-09-11T06:00:00+01:00,2025-09-11,05:00,Aveiro,Santa Maria da Feira,"Lobão, Gião, Louredo e Guisande",0.00,1,109,010934,01_a_10,11,9,2025
4948485,2025-09-17T05:00:00+01:00,2025-09-17,04:00,Aveiro,Santa Maria da Feira,"Lobão, Gião, Louredo e Guisande",0.00,1,109,010934,01_a_10,17,9,2025
4948489,2025-09-11T19:00:00+01:00,2025-09-11,18:00,Aveiro,Santa Maria da Feira,Arrifana,26.22,1,109,010902,01_a_10,11,9,2025
4948511,2025-09-21T14:00:00+01:00,2025-09-21,13:00,Aveiro,Oliveira de Azeméis,Nogueira do Cravo e Pindelo,0.00,1,113,011320,01_a_10,21,9,2025

,Date/Time,Date,Hour,District,Municipality,Parish,Energy Consumed,District Code,Municipality Code,Parish Code,group_name,Dia,Mês,Ano
18,2025-10-02T18:00:00+01:00,2025-10-02,17:00,Porto,Vila Nova de Gaia,Avintes,0.52,13,1317,131702,11_a_18,2,10,2025
19,2025-10-04T09:00:00+01:00,2025-10-04,08:00,Porto,Vila Nova de Gaia,Avintes,2.72,13,1317,131702,11_a_18,4,10,2025
20,2025-10-28T12:00:00+00:00,2025-10-28,12:00,Porto,Vila Nova de Gaia,Avintes,33.80,13,1317,131702,11_a_18,28,10,2025
21,2025-10-18T11:00:00+01:00,2025-10-18,10:00,Porto,Vila Nova de Gaia,Avintes,22.46,13,1317,131702,11_a_18,18,10,2025
27,2025-10-04T13:00:00+01:00,2025-10-04,12:00,Porto,Vila do Conde,"Bagunte, Ferreiró, Outeiro Maior e Parada",1.51,13,1316,131631,11_a_18,4,10,2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4366639,2026-01-16T07:00:00+00:00,2026-01-16,07:00,Porto,Vila do Conde,"Bagunte, Ferreiró, Outeiro Maior e Parada",0.00,13,1316,131631,11_a_18,16,1,2026
4366640,2026-01-22T15:00:00+00:00,2026-01-22,15:00,Porto,Vila do Conde,"Bagunte, Ferreiró, Outeiro Maior e Parada",1.07,13,1316,131631,11_a_18,22,1,2026
4366674,2026-01-30T07:00:00+00:00,2026-01-30,07:00,Porto,Vila Nova de Gaia,Avintes,43.40,13,1317,131702,11_a_18,30,1,2026
4366675,2026-01-02T14:00:00+00:00,2026-01-02,14:00,Porto,Vila do Conde,"Bagunte, Ferreiró, Outeiro Maior e Parada",0.00,13,1316,131631,11_a_18,2,1,2026
4366688,2026-01-20T11:00:00+00:00,2026-01-20,11:00,Porto,Paredes,Vandoma,0.00,13,1310,131022,11_a_18,20,1,2026

In [25]:
# Join both datasets so we have all information for the Area Metropolitan of Porto
df_consumption_amp = pd.concat([df_consumption_pt1, df_consumption_pt2], axis=0, ignore_index=True)
df_consumption_amp

,Date/Time,Date,Hour,District,Municipality,Parish,Energy Consumed,District Code,Municipality Code,Parish Code,group_name,Dia,Mês,Ano
0,2025-10-01T05:00:00+01:00,2025-10-01,04:00,Aveiro,Santa Maria da Feira,Milheirós de Poiares,0.00,1,109,010914,01_a_10,1,10,2025
1,2025-10-05T00:00:00+01:00,2025-10-04,23:00,Aveiro,Santa Maria da Feira,Milheirós de Poiares,0.00,1,109,010914,01_a_10,4,10,2025
2,2025-10-26T23:00:00+00:00,2025-10-26,23:00,Aveiro,Santa Maria da Feira,Milheirós de Poiares,0.00,1,109,010914,01_a_10,26,10,2025
3,2025-10-22T04:00:00+01:00,2025-10-22,03:00,Aveiro,Santa Maria da Feira,Milheirós de Poiares,0.00,1,109,010914,01_a_10,22,10,2025
4,2025-10-10T12:00:00+01:00,2025-10-10,11:00,Aveiro,Santa Maria da Feira,Milheirós de Poiares,0.00,1,109,010914,01_a_10,10,10,2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027227,2026-01-16T07:00:00+00:00,2026-01-16,07:00,Porto,Vila do Conde,"Bagunte, Ferreiró, Outeiro Maior e Parada",0.00,13,1316,131631,11_a_18,16,1,2026
1027228,2026-01-22T15:00:00+00:00,2026-01-22,15:00,Porto,Vila do Conde,"Bagunte, Ferreiró, Outeiro Maior e Parada",1.07,13,1316,131631,11_a_18,22,1,2026
1027229,2026-01-30T07:00:00+00:00,2026-01-30,07:00,Porto,Vila Nova de Gaia,Avintes,43.40,13,1317,131702,11_a_18,30,1,2026
1027230,2026-01-02T14:00:00+00:00,2026-01-02,14:00,Porto,Vila do Conde,"Bagunte, Ferreiró, Outeiro Maior e Parada",0.00,13,1316,131631,11_a_18,2,1,2026
1027231,2026-01-20T11:00:00+00:00,2026-01-20,11:00,Porto,Paredes,Vandoma,0.00,13,1310,131022,11_a_18,20,1,2026

In [26]:
df_consumption_amp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1027232 entries, 0 to 1027231
Data columns (total 14 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   Date/Time          1027232 non-null  object
 1   Date               1027232 non-null  object
 2   Hour               1027232 non-null  object
 3   District           1027232 non-null  object
 4   Municipality       1027232 non-null  object
 5   Parish             1027232 non-null  object
 6   Energy Consumed    1027232 non-null  float64
 7   District Code      1027232 non-null  int64
 8   Municipality Code  1027232 non-null  int64
 9   Parish Code        1027232 non-null  object
 10  group_name         1027232 non-null  object
 11  Dia                1027232 non-null  int64
 12  Mês                1027232 non-null  int64
 13  Ano                1027232 non-null  int64
dtypes: float64(1), int64(5), object(8)
memory usage: 109.7+ MB

In [27]:
df_consumption_amp.to_csv('cleaned_consumo_horario_mobilidade_eletrica.csv')

# Charging Points Dataset


Number of Outlets at charging points by geographic location (NUTS - 2024) and outlet type; Monthly

Source: Instituto Nacional de Estatística (INE)

https://www.ine.pt/xportal/xmain?xpid=INE&xpgid=ine_indicadores&indOcorrCod=0014692&contexto=bd&selTab=tab2

In [89]:
df_charging = pd.read_csv(
    "ine_charging_points_number_location.csv",
    encoding="latin1",
    sep=";",
    skiprows=3
    )

df_charging

,Localização geográfica (NUTS - 2024),Tomadas (N.º) nos pontos de carregamento por Localização geográfica (NUTS - 2024) e Tipo de tomada - Mensal,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 232,Unnamed: 233,Unnamed: 234,Unnamed: 235,Unnamed: 236,Unnamed: 237,Unnamed: 238,Unnamed: 239,Unnamed: 240,Unnamed: 241
0,NaN,Período de referência dos dados,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Dezembro de 2024,NaN,NaN,NaN,NaN,Novembro de 2024,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Janeiro de 2021,NaN,NaN,NaN,NaN,NaN
2,NaN,Tipo de tomada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Total,Mennekes,CHAdeMO,CCS,Industrial,Total,Mennekes,CHAdeMO,CCS,...,Mennekes,CHAdeMO,CCS,Industrial,Total,Mennekes,CHAdeMO,CCS,Industrial,NaN
4,NaN,N.º,N.º,N.º,N.º,N.º,N.º,N.º,N.º,N.º,...,N.º,N.º,N.º,N.º,N.º,N.º,N.º,N.º,N.º,NaN
5,11A: Área Metropolitana do Porto,2388,1584,326,478,- -,2323,1541,324,458,...,276,54,55,- -,347,250,48,49,- -,NaN
6,11A0104: Arouca,9,7,1,1,- -,9,7,1,1,...,2,- -,- -,- -,4,4,- -,- -,- -,NaN
7,11A0107: Espinho,25,17,4,4,- -,24,16,4,4,...,2,- -,- -,- -,2,2,- -,- -,- -,NaN
8,11A1304: Gondomar,113,69,16,28,- -,112,68,16,28,...,3,3,3,- -,3,1,1,1,- -,NaN
9,11A1306: Maia,177,130,19,28,- -,177,130,19,28,...,16,4,4,- -,14,10,2,2,- -,NaN
10,11A1308: Matosinhos,357,243,39,75,- -,355,246,39,70,...,45,7,9,- -,61,45,7,9,- -,NaN
11,11A0113: Oliveira de Azeméis,24,15,4,5,- -,24,15,4,5,...,2,- -,- -,- -,2,2,- -,- -,- -,NaN
12,11A1310: Paredes,62,29,12,21,- -,54,29,12,13,...,4,- -,- -,- -,4,4,- -,- -,- -,NaN
13,11A1312: Porto,566,411,71,84,- -,548,395,70,83,...,87,17,17,- -,102,70,16,16,- -,NaN
14,11A1313: Póvoa de Varzim,88,53,12,23,- -,88,53,12,23,...,4,2,2,- -,8,4,2,2,- -,NaN
15,11A0109: Santa Maria da Feira,194,135,21,38,- -,185,131,20,34,...,6,4,4,- -,11,5,3,3,- -,NaN
16,11A1314: Santo Tirso,62,30,15,17,- -,59,27,15,17,...,5,3,3,- -,9,3,3,3,- -,NaN
17,11A0116: São João da Madeira,65,53,5,7,- -,51,39,5,7,...,2,- -,- -,- -,2,2,- -,- -,- -,NaN
18,11A1318: Trofa,33,15,8,10,- -,33,15,8,10,...,4,- -,- -,- -,4,4,- -,- -,- -,NaN
19,11A0119: Vale de Cambra,12,5,4,3,- -,12,5,4,3,...,6,- -,- -,- -,6,6,- -,- -,- -,NaN
20,11A1315: Valongo,104,53,20,31,- -,101,52,20,29,...,5,3,2,- -,10,5,3,2,- -,NaN
21,11A1316: Vila do Conde,95,63,11,21,- -,94,62,11,21,...,12,2,2,- -,16,12,2,2,- -,NaN
22,11A1317: Vila Nova de Gaia,402,256,64,82,- -,397,251,64,82,...,71,9,9,- -,89,71,9,9,- -,NaN
23,Tomadas (N.º) nos pontos de carregamento por L...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Última atualização destes dados: 27 de março d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Metainformação associada ao quadro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Tomadas (N.º) nos pontos de carregamento,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Designação,Tomadas (N.º) nos pontos de carregamento por L...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Periodicidade,Anual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Fonte,"Mobi.E, Entidade gestora da rede de mobilidade...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Primeiro período disponível,Janeiro de 2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Último período disponível,Dezembro de 2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Dimensões,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Dimensão 1,Período de referência dos dados (Mês),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Dimensão 2,Localização geográfica (NUTS - 2024),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Dimensão 3,Tipo de tomada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Conceitos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,TIPO DE TOMADA,Tomada utilizada para fazer a ligação entre o ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,PERÍODO DE REFERÊNCIA,Período a que a informação se refere e que pod...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,PONTO DE CARREGAMENTO,"Interface fixa ou móvel, ligada ou não à rede ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,TOMADA,Terminal de instalação elétrica constituído po...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Definição,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Fórmula,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Unidade de Medida (símbolo),Número (N.º),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,Potência de 10,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Data da última atualização,27-Mar-2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [90]:
row_period = df_charging.iloc[1]
row_type = df_charging.iloc[3]

columns = []
current_period = None

for i in range(len(df_charging.columns)):
    if pd.notna(row_period[i]):
        current_period = row_period[i]
    
    socket_type = row_type[i]
    
    if i == 0:
        columns.append("region")
    elif pd.notna(socket_type):
        columns.append(f"{current_period} | {socket_type}")
    else:
        columns.append(None)

df_charging.columns = columns

df_charging

C:\Users\InesNeves\AppData\Local\Temp\ipykernel_34992\2877574677.py:8: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if pd.notna(row_period[i]):
C:\Users\InesNeves\AppData\Local\Temp\ipykernel_34992\2877574677.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  socket_type = row_type[i]
C:\Users\InesNeves\AppData\Local\Temp\ipykernel_34992\2877574677.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  current_period = row_period[i]

,region,Dezembro de 2024 | Total,Dezembro de 2024 | Mennekes,Dezembro de 2024 | CHAdeMO,Dezembro de 2024 | CCS,Dezembro de 2024 | Industrial,Novembro de 2024 | Total,Novembro de 2024 | Mennekes,Novembro de 2024 | CHAdeMO,Novembro de 2024 | CCS,...,Fevereiro de 2021 | Mennekes,Fevereiro de 2021 | CHAdeMO,Fevereiro de 2021 | CCS,Fevereiro de 2021 | Industrial,Janeiro de 2021 | Total,Janeiro de 2021 | Mennekes,Janeiro de 2021 | CHAdeMO,Janeiro de 2021 | CCS,Janeiro de 2021 | Industrial,None
0,NaN,Período de referência dos dados,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Dezembro de 2024,NaN,NaN,NaN,NaN,Novembro de 2024,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Janeiro de 2021,NaN,NaN,NaN,NaN,NaN
2,NaN,Tipo de tomada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Total,Mennekes,CHAdeMO,CCS,Industrial,Total,Mennekes,CHAdeMO,CCS,...,Mennekes,CHAdeMO,CCS,Industrial,Total,Mennekes,CHAdeMO,CCS,Industrial,NaN
4,NaN,N.º,N.º,N.º,N.º,N.º,N.º,N.º,N.º,N.º,...,N.º,N.º,N.º,N.º,N.º,N.º,N.º,N.º,N.º,NaN
5,11A: Área Metropolitana do Porto,2388,1584,326,478,- -,2323,1541,324,458,...,276,54,55,- -,347,250,48,49,- -,NaN
6,11A0104: Arouca,9,7,1,1,- -,9,7,1,1,...,2,- -,- -,- -,4,4,- -,- -,- -,NaN
7,11A0107: Espinho,25,17,4,4,- -,24,16,4,4,...,2,- -,- -,- -,2,2,- -,- -,- -,NaN
8,11A1304: Gondomar,113,69,16,28,- -,112,68,16,28,...,3,3,3,- -,3,1,1,1,- -,NaN
9,11A1306: Maia,177,130,19,28,- -,177,130,19,28,...,16,4,4,- -,14,10,2,2,- -,NaN
10,11A1308: Matosinhos,357,243,39,75,- -,355,246,39,70,...,45,7,9,- -,61,45,7,9,- -,NaN
11,11A0113: Oliveira de Azeméis,24,15,4,5,- -,24,15,4,5,...,2,- -,- -,- -,2,2,- -,- -,- -,NaN
12,11A1310: Paredes,62,29,12,21,- -,54,29,12,13,...,4,- -,- -,- -,4,4,- -,- -,- -,NaN
13,11A1312: Porto,566,411,71,84,- -,548,395,70,83,...,87,17,17,- -,102,70,16,16,- -,NaN
14,11A1313: Póvoa de Varzim,88,53,12,23,- -,88,53,12,23,...,4,2,2,- -,8,4,2,2,- -,NaN
15,11A0109: Santa Maria da Feira,194,135,21,38,- -,185,131,20,34,...,6,4,4,- -,11,5,3,3,- -,NaN
16,11A1314: Santo Tirso,62,30,15,17,- -,59,27,15,17,...,5,3,3,- -,9,3,3,3,- -,NaN
17,11A0116: São João da Madeira,65,53,5,7,- -,51,39,5,7,...,2,- -,- -,- -,2,2,- -,- -,- -,NaN
18,11A1318: Trofa,33,15,8,10,- -,33,15,8,10,...,4,- -,- -,- -,4,4,- -,- -,- -,NaN
19,11A0119: Vale de Cambra,12,5,4,3,- -,12,5,4,3,...,6,- -,- -,- -,6,6,- -,- -,- -,NaN
20,11A1315: Valongo,104,53,20,31,- -,101,52,20,29,...,5,3,2,- -,10,5,3,2,- -,NaN
21,11A1316: Vila do Conde,95,63,11,21,- -,94,62,11,21,...,12,2,2,- -,16,12,2,2,- -,NaN
22,11A1317: Vila Nova de Gaia,402,256,64,82,- -,397,251,64,82,...,71,9,9,- -,89,71,9,9,- -,NaN
23,Tomadas (N.º) nos pontos de carregamento por L...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Última atualização destes dados: 27 de março d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Metainformação associada ao quadro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Tomadas (N.º) nos pontos de carregamento,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Designação,Tomadas (N.º) nos pontos de carregamento por L...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Periodicidade,Anual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Fonte,"Mobi.E, Entidade gestora da rede de mobilidade...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Primeiro período disponível,Janeiro de 2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Último período disponível,Dezembro de 2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Dimensões,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Dimensão 1,Período de referência dos dados (Mês),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Dimensão 2,Localização geográfica (NUTS - 2024),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Dimensão 3,Tipo de tomada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Conceitos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,TIPO DE TOMADA,Tomada utilizada para fazer a ligação entre o ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,PERÍODO DE REFERÊNCIA,Período a que a informação se refere e que pod...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,PONTO DE CARREGAMENTO,"Interface fixa ou móvel, ligada ou não à rede ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,TOMADA,Terminal de instalação elétrica constituído po...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Definição,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Fórmula,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Unidade de Medida (símbolo),Número (N.º),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,Potência de 10,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Data da última atualização,27-Mar-2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [91]:
# Remove header rows
df_charging = df_charging.iloc[5:].reset_index(drop=True)

# Remove empty columns
df_charging = df_charging.loc[:, df_charging.columns.notna()]

# Remove duplicate columns
df_charging = df_charging.loc[:, ~df_charging.columns.duplicated()]

df_charging = df_charging.replace("- -", pd.NA)

df_charging

,region,Dezembro de 2024 | Total,Dezembro de 2024 | Mennekes,Dezembro de 2024 | CHAdeMO,Dezembro de 2024 | CCS,Dezembro de 2024 | Industrial,Novembro de 2024 | Total,Novembro de 2024 | Mennekes,Novembro de 2024 | CHAdeMO,Novembro de 2024 | CCS,...,Fevereiro de 2021 | Total,Fevereiro de 2021 | Mennekes,Fevereiro de 2021 | CHAdeMO,Fevereiro de 2021 | CCS,Fevereiro de 2021 | Industrial,Janeiro de 2021 | Total,Janeiro de 2021 | Mennekes,Janeiro de 2021 | CHAdeMO,Janeiro de 2021 | CCS,Janeiro de 2021 | Industrial
0,11A: Área Metropolitana do Porto,2388,1584,326,478,<NA>,2323,1541,324,458,...,385,276,54,55,<NA>,347,250,48,49,<NA>
1,11A0104: Arouca,9,7,1,1,<NA>,9,7,1,1,...,2,2,<NA>,<NA>,<NA>,4,4,<NA>,<NA>,<NA>
2,11A0107: Espinho,25,17,4,4,<NA>,24,16,4,4,...,2,2,<NA>,<NA>,<NA>,2,2,<NA>,<NA>,<NA>
3,11A1304: Gondomar,113,69,16,28,<NA>,112,68,16,28,...,9,3,3,3,<NA>,3,1,1,1,<NA>
4,11A1306: Maia,177,130,19,28,<NA>,177,130,19,28,...,24,16,4,4,<NA>,14,10,2,2,<NA>
5,11A1308: Matosinhos,357,243,39,75,<NA>,355,246,39,70,...,61,45,7,9,<NA>,61,45,7,9,<NA>
6,11A0113: Oliveira de Azeméis,24,15,4,5,<NA>,24,15,4,5,...,2,2,<NA>,<NA>,<NA>,2,2,<NA>,<NA>,<NA>
7,11A1310: Paredes,62,29,12,21,<NA>,54,29,12,13,...,4,4,<NA>,<NA>,<NA>,4,4,<NA>,<NA>,<NA>
8,11A1312: Porto,566,411,71,84,<NA>,548,395,70,83,...,121,87,17,17,<NA>,102,70,16,16,<NA>
9,11A1313: Póvoa de Varzim,88,53,12,23,<NA>,88,53,12,23,...,8,4,2,2,<NA>,8,4,2,2,<NA>
10,11A0109: Santa Maria da Feira,194,135,21,38,<NA>,185,131,20,34,...,14,6,4,4,<NA>,11,5,3,3,<NA>
11,11A1314: Santo Tirso,62,30,15,17,<NA>,59,27,15,17,...,11,5,3,3,<NA>,9,3,3,3,<NA>
12,11A0116: São João da Madeira,65,53,5,7,<NA>,51,39,5,7,...,2,2,<NA>,<NA>,<NA>,2,2,<NA>,<NA>,<NA>
13,11A1318: Trofa,33,15,8,10,<NA>,33,15,8,10,...,4,4,<NA>,<NA>,<NA>,4,4,<NA>,<NA>,<NA>
14,11A0119: Vale de Cambra,12,5,4,3,<NA>,12,5,4,3,...,6,6,<NA>,<NA>,<NA>,6,6,<NA>,<NA>,<NA>
15,11A1315: Valongo,104,53,20,31,<NA>,101,52,20,29,...,10,5,3,2,<NA>,10,5,3,2,<NA>
16,11A1316: Vila do Conde,95,63,11,21,<NA>,94,62,11,21,...,16,12,2,2,<NA>,16,12,2,2,<NA>
17,11A1317: Vila Nova de Gaia,402,256,64,82,<NA>,397,251,64,82,...,89,71,9,9,<NA>,89,71,9,9,<NA>
18,Tomadas (N.º) nos pontos de carregamento por L...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Última atualização destes dados: 27 de março d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Metainformação associada ao quadro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Tomadas (N.º) nos pontos de carregamento,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Designação,Tomadas (N.º) nos pontos de carregamento por L...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Periodicidade,Anual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Fonte,"Mobi.E, Entidade gestora da rede de mobilidade...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Primeiro período disponível,Janeiro de 2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Último período disponível,Dezembro de 2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Dimensões,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Dimensão 1,Período de referência dos dados (Mês),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Dimensão 2,Localização geográfica (NUTS - 2024),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Dimensão 3,Tipo de tomada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Conceitos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,TIPO DE TOMADA,Tomada utilizada para fazer a ligação entre o ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,PERÍODO DE REFERÊNCIA,Período a que a informação se refere e que pod...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,PONTO DE CARREGAMENTO,"Interface fixa ou móvel, ligada ou não à rede ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,TOMADA,Terminal de instalação elétrica constituído po...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Definição,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Fórmula,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Unidade de Medida (símbolo),Número (N.º),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Potência de 10,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Data da última atualização,27-Mar-2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [92]:
#Select data of interest
df_charging = df_charging.iloc[0:18]
df_charging

,region,Dezembro de 2024 | Total,Dezembro de 2024 | Mennekes,Dezembro de 2024 | CHAdeMO,Dezembro de 2024 | CCS,Dezembro de 2024 | Industrial,Novembro de 2024 | Total,Novembro de 2024 | Mennekes,Novembro de 2024 | CHAdeMO,Novembro de 2024 | CCS,...,Fevereiro de 2021 | Total,Fevereiro de 2021 | Mennekes,Fevereiro de 2021 | CHAdeMO,Fevereiro de 2021 | CCS,Fevereiro de 2021 | Industrial,Janeiro de 2021 | Total,Janeiro de 2021 | Mennekes,Janeiro de 2021 | CHAdeMO,Janeiro de 2021 | CCS,Janeiro de 2021 | Industrial
0,11A: Área Metropolitana do Porto,2388,1584,326,478,<NA>,2323,1541,324,458,...,385,276,54,55,<NA>,347,250,48,49,<NA>
1,11A0104: Arouca,9,7,1,1,<NA>,9,7,1,1,...,2,2,<NA>,<NA>,<NA>,4,4,<NA>,<NA>,<NA>
2,11A0107: Espinho,25,17,4,4,<NA>,24,16,4,4,...,2,2,<NA>,<NA>,<NA>,2,2,<NA>,<NA>,<NA>
3,11A1304: Gondomar,113,69,16,28,<NA>,112,68,16,28,...,9,3,3,3,<NA>,3,1,1,1,<NA>
4,11A1306: Maia,177,130,19,28,<NA>,177,130,19,28,...,24,16,4,4,<NA>,14,10,2,2,<NA>
5,11A1308: Matosinhos,357,243,39,75,<NA>,355,246,39,70,...,61,45,7,9,<NA>,61,45,7,9,<NA>
6,11A0113: Oliveira de Azeméis,24,15,4,5,<NA>,24,15,4,5,...,2,2,<NA>,<NA>,<NA>,2,2,<NA>,<NA>,<NA>
7,11A1310: Paredes,62,29,12,21,<NA>,54,29,12,13,...,4,4,<NA>,<NA>,<NA>,4,4,<NA>,<NA>,<NA>
8,11A1312: Porto,566,411,71,84,<NA>,548,395,70,83,...,121,87,17,17,<NA>,102,70,16,16,<NA>
9,11A1313: Póvoa de Varzim,88,53,12,23,<NA>,88,53,12,23,...,8,4,2,2,<NA>,8,4,2,2,<NA>
10,11A0109: Santa Maria da Feira,194,135,21,38,<NA>,185,131,20,34,...,14,6,4,4,<NA>,11,5,3,3,<NA>
11,11A1314: Santo Tirso,62,30,15,17,<NA>,59,27,15,17,...,11,5,3,3,<NA>,9,3,3,3,<NA>
12,11A0116: São João da Madeira,65,53,5,7,<NA>,51,39,5,7,...,2,2,<NA>,<NA>,<NA>,2,2,<NA>,<NA>,<NA>
13,11A1318: Trofa,33,15,8,10,<NA>,33,15,8,10,...,4,4,<NA>,<NA>,<NA>,4,4,<NA>,<NA>,<NA>
14,11A0119: Vale de Cambra,12,5,4,3,<NA>,12,5,4,3,...,6,6,<NA>,<NA>,<NA>,6,6,<NA>,<NA>,<NA>
15,11A1315: Valongo,104,53,20,31,<NA>,101,52,20,29,...,10,5,3,2,<NA>,10,5,3,2,<NA>
16,11A1316: Vila do Conde,95,63,11,21,<NA>,94,62,11,21,...,16,12,2,2,<NA>,16,12,2,2,<NA>
17,11A1317: Vila Nova de Gaia,402,256,64,82,<NA>,397,251,64,82,...,89,71,9,9,<NA>,89,71,9,9,<NA>

In [93]:
df_charging[["code", "region"]] = df_charging["region"].str.split(": ", expand=True)
df_charging

C:\Users\InesNeves\AppData\Local\Temp\ipykernel_34992\3007277496.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_charging[["code", "region"]] = df_charging["region"].str.split(": ", expand=True)

,region,Dezembro de 2024 | Total,Dezembro de 2024 | Mennekes,Dezembro de 2024 | CHAdeMO,Dezembro de 2024 | CCS,Dezembro de 2024 | Industrial,Novembro de 2024 | Total,Novembro de 2024 | Mennekes,Novembro de 2024 | CHAdeMO,Novembro de 2024 | CCS,...,Fevereiro de 2021 | Mennekes,Fevereiro de 2021 | CHAdeMO,Fevereiro de 2021 | CCS,Fevereiro de 2021 | Industrial,Janeiro de 2021 | Total,Janeiro de 2021 | Mennekes,Janeiro de 2021 | CHAdeMO,Janeiro de 2021 | CCS,Janeiro de 2021 | Industrial,code
0,Área Metropolitana do Porto,2388,1584,326,478,<NA>,2323,1541,324,458,...,276,54,55,<NA>,347,250,48,49,<NA>,11A
1,Arouca,9,7,1,1,<NA>,9,7,1,1,...,2,<NA>,<NA>,<NA>,4,4,<NA>,<NA>,<NA>,11A0104
2,Espinho,25,17,4,4,<NA>,24,16,4,4,...,2,<NA>,<NA>,<NA>,2,2,<NA>,<NA>,<NA>,11A0107
3,Gondomar,113,69,16,28,<NA>,112,68,16,28,...,3,3,3,<NA>,3,1,1,1,<NA>,11A1304
4,Maia,177,130,19,28,<NA>,177,130,19,28,...,16,4,4,<NA>,14,10,2,2,<NA>,11A1306
5,Matosinhos,357,243,39,75,<NA>,355,246,39,70,...,45,7,9,<NA>,61,45,7,9,<NA>,11A1308
6,Oliveira de Azeméis,24,15,4,5,<NA>,24,15,4,5,...,2,<NA>,<NA>,<NA>,2,2,<NA>,<NA>,<NA>,11A0113
7,Paredes,62,29,12,21,<NA>,54,29,12,13,...,4,<NA>,<NA>,<NA>,4,4,<NA>,<NA>,<NA>,11A1310
8,Porto,566,411,71,84,<NA>,548,395,70,83,...,87,17,17,<NA>,102,70,16,16,<NA>,11A1312
9,Póvoa de Varzim,88,53,12,23,<NA>,88,53,12,23,...,4,2,2,<NA>,8,4,2,2,<NA>,11A1313
10,Santa Maria da Feira,194,135,21,38,<NA>,185,131,20,34,...,6,4,4,<NA>,11,5,3,3,<NA>,11A0109
11,Santo Tirso,62,30,15,17,<NA>,59,27,15,17,...,5,3,3,<NA>,9,3,3,3,<NA>,11A1314
12,São João da Madeira,65,53,5,7,<NA>,51,39,5,7,...,2,<NA>,<NA>,<NA>,2,2,<NA>,<NA>,<NA>,11A0116
13,Trofa,33,15,8,10,<NA>,33,15,8,10,...,4,<NA>,<NA>,<NA>,4,4,<NA>,<NA>,<NA>,11A1318
14,Vale de Cambra,12,5,4,3,<NA>,12,5,4,3,...,6,<NA>,<NA>,<NA>,6,6,<NA>,<NA>,<NA>,11A0119
15,Valongo,104,53,20,31,<NA>,101,52,20,29,...,5,3,2,<NA>,10,5,3,2,<NA>,11A1315
16,Vila do Conde,95,63,11,21,<NA>,94,62,11,21,...,12,2,2,<NA>,16,12,2,2,<NA>,11A1316
17,Vila Nova de Gaia,402,256,64,82,<NA>,397,251,64,82,...,71,9,9,<NA>,89,71,9,9,<NA>,11A1317

In [94]:
df_long = df_charging.melt(
    id_vars=["code", "region"],
    var_name="Period_Type",
    value_name="Value"
)
df_long

         code                       region                   Period_Type Value
0         11A  Área Metropolitana do Porto      Dezembro de 2024 | Total  2388
1     11A0104                       Arouca      Dezembro de 2024 | Total     9
2     11A0107                      Espinho      Dezembro de 2024 | Total    25
3     11A1304                     Gondomar      Dezembro de 2024 | Total   113
4     11A1306                         Maia      Dezembro de 2024 | Total   177
...       ...                          ...                           ...   ...
4315  11A1318                        Trofa  Janeiro de 2021 | Industrial  <NA>
4316  11A0119               Vale de Cambra  Janeiro de 2021 | Industrial  <NA>
4317  11A1315                      Valongo  Janeiro de 2021 | Industrial  <NA>
4318  11A1316                Vila do Conde  Janeiro de 2021 | Industrial  <NA>
4319  11A1317            Vila Nova de Gaia  Janeiro de 2021 | Industrial  <NA>

[4320 rows x 4 columns]

In [95]:
df_long[["Period", "Outlet_Type"]] = df_long["Period_Type"].str.split(
    " | ", expand=True, regex=False
)
df_long

,code,region,Period_Type,Value,Period,Outlet_Type
0,11A,Área Metropolitana do Porto,Dezembro de 2024 | Total,2388,Dezembro de 2024,Total
1,11A0104,Arouca,Dezembro de 2024 | Total,9,Dezembro de 2024,Total
2,11A0107,Espinho,Dezembro de 2024 | Total,25,Dezembro de 2024,Total
3,11A1304,Gondomar,Dezembro de 2024 | Total,113,Dezembro de 2024,Total
4,11A1306,Maia,Dezembro de 2024 | Total,177,Dezembro de 2024,Total
...,...,...,...,...,...,...
4315,11A1318,Trofa,Janeiro de 2021 | Industrial,<NA>,Janeiro de 2021,Industrial
4316,11A0119,Vale de Cambra,Janeiro de 2021 | Industrial,<NA>,Janeiro de 2021,Industrial
4317,11A1315,Valongo,Janeiro de 2021 | Industrial,<NA>,Janeiro de 2021,Industrial
4318,11A1316,Vila do Conde,Janeiro de 2021 | Industrial,<NA>,Janeiro de 2021,Industrial
4319,11A1317,Vila Nova de Gaia,Janeiro de 2021 | Industrial,<NA>,Janeiro de 2021,Industrial

In [96]:
df_long = df_long.drop('Period_Type', axis=1)
df_long

         code                       region Value            Period Outlet_Type
0         11A  Área Metropolitana do Porto  2388  Dezembro de 2024       Total
1     11A0104                       Arouca     9  Dezembro de 2024       Total
2     11A0107                      Espinho    25  Dezembro de 2024       Total
3     11A1304                     Gondomar   113  Dezembro de 2024       Total
4     11A1306                         Maia   177  Dezembro de 2024       Total
...       ...                          ...   ...               ...         ...
4315  11A1318                        Trofa  <NA>   Janeiro de 2021  Industrial
4316  11A0119               Vale de Cambra  <NA>   Janeiro de 2021  Industrial
4317  11A1315                      Valongo  <NA>   Janeiro de 2021  Industrial
4318  11A1316                Vila do Conde  <NA>   Janeiro de 2021  Industrial
4319  11A1317            Vila Nova de Gaia  <NA>   Janeiro de 2021  Industrial

[4320 rows x 5 columns]

In [97]:
# Extracting the year 
df_long["year"] = df_long["Period"].str.extract(r"(\d{4})").astype(int)

#Extracting the month
df_long["month_name"] = df_long["Period"].str.extract(r"^([A-Za-zçÇ]+)")

df_long

,code,region,Value,Period,Outlet_Type,year,month_name
0,11A,Área Metropolitana do Porto,2388,Dezembro de 2024,Total,2024,Dezembro
1,11A0104,Arouca,9,Dezembro de 2024,Total,2024,Dezembro
2,11A0107,Espinho,25,Dezembro de 2024,Total,2024,Dezembro
3,11A1304,Gondomar,113,Dezembro de 2024,Total,2024,Dezembro
4,11A1306,Maia,177,Dezembro de 2024,Total,2024,Dezembro
...,...,...,...,...,...,...,...
4315,11A1318,Trofa,<NA>,Janeiro de 2021,Industrial,2021,Janeiro
4316,11A0119,Vale de Cambra,<NA>,Janeiro de 2021,Industrial,2021,Janeiro
4317,11A1315,Valongo,<NA>,Janeiro de 2021,Industrial,2021,Janeiro
4318,11A1316,Vila do Conde,<NA>,Janeiro de 2021,Industrial,2021,Janeiro
4319,11A1317,Vila Nova de Gaia,<NA>,Janeiro de 2021,Industrial,2021,Janeiro

In [98]:
# Map the Month_names into numbers
month_map = {
    "Janeiro": 1,
    "Fevereiro": 2,
    "Março": 3,
    "Abril": 4,
    "Maio": 5,
    "Junho": 6,
    "Julho": 7,
    "Agosto": 8,
    "Setembro": 9,
    "Outubro": 10,
    "Novembro": 11,
    "Dezembro": 12
}

df_long["month"] = df_long["month_name"].map(month_map)
df_long

,code,region,Value,Period,Outlet_Type,year,month_name,month
0,11A,Área Metropolitana do Porto,2388,Dezembro de 2024,Total,2024,Dezembro,12
1,11A0104,Arouca,9,Dezembro de 2024,Total,2024,Dezembro,12
2,11A0107,Espinho,25,Dezembro de 2024,Total,2024,Dezembro,12
3,11A1304,Gondomar,113,Dezembro de 2024,Total,2024,Dezembro,12
4,11A1306,Maia,177,Dezembro de 2024,Total,2024,Dezembro,12
...,...,...,...,...,...,...,...,...
4315,11A1318,Trofa,<NA>,Janeiro de 2021,Industrial,2021,Janeiro,1
4316,11A0119,Vale de Cambra,<NA>,Janeiro de 2021,Industrial,2021,Janeiro,1
4317,11A1315,Valongo,<NA>,Janeiro de 2021,Industrial,2021,Janeiro,1
4318,11A1316,Vila do Conde,<NA>,Janeiro de 2021,Industrial,2021,Janeiro,1
4319,11A1317,Vila Nova de Gaia,<NA>,Janeiro de 2021,Industrial,2021,Janeiro,1

In [99]:
df_charging = df_long.drop(columns=["month_name"])
df_charging = df_charging.drop(columns=["Period"])

df_charging

         code                       region Value Outlet_Type  year  month
0         11A  Área Metropolitana do Porto  2388       Total  2024     12
1     11A0104                       Arouca     9       Total  2024     12
2     11A0107                      Espinho    25       Total  2024     12
3     11A1304                     Gondomar   113       Total  2024     12
4     11A1306                         Maia   177       Total  2024     12
...       ...                          ...   ...         ...   ...    ...
4315  11A1318                        Trofa  <NA>  Industrial  2021      1
4316  11A0119               Vale de Cambra  <NA>  Industrial  2021      1
4317  11A1315                      Valongo  <NA>  Industrial  2021      1
4318  11A1316                Vila do Conde  <NA>  Industrial  2021      1
4319  11A1317            Vila Nova de Gaia  <NA>  Industrial  2021      1

[4320 rows x 6 columns]

In [100]:
df_charging.to_csv('cleaned_ine_charging_points_number_location.csv')